const router = {
  ABOUT: "/about",
  SOLUTION: "/solution",
  CAREER: "/career",
  ENGAGEMENTSMODELS:"/engagement-models",
  INFRASTRUCTURE:"/infrastructure",

  HireWordPressDeveloper: "/hire-wordpress-developer",
  HireGraphicsDesigner: "/hire-graphics-designer",
  HireWebDesigner: "/hire-web-designer",
  HIREUIUXDESIGNER: "/hire-uiux-designer",
  HirePHPDeveloper: "/hire-php-developer",
  HIREDOTNETDEVELOPER: "/hire-dot-net-developer",
  HIRLARAVELDEVELOPER: "/hire-laravel-developer",
  HIRCODEIGNITERDEVELOPER: "/hire-codeigniter-developer",
  HIRSHOPIFYRDEVELOPER: "/hire-shopify-developer",
  HireAndroidDeveloper: "/hire-android-developer",
  HireFlutterDeveloper: "/hire-flutter-developer",
  HireReactJSDeveloper: "/hire-react-js-developer",
  HireNodeJSDeveloper: "/hire-node-js-developer",
  HireWebflowDeveloper: "/hire-webflow-developer",
  HirehubspotDeveloper: "/hire-hubspot-developer",
  HireiosDeveloper: "/hire-ios-developer",
  HireionicDeveloper: "/hire-ionic-developer",
  HireReactNativeDeveloper: "/hire-react-native-developer",
  HireExpressDeveloper: "/hire-express-developer",
  HireNextJSDeveloper: "/hire-nextjs-developer",
  HireAngularJSDeveloper: "/hire-angularjs-developer",

  
  GRAPHICSDESIGN: "/graphics-design",
  WEBDESIGN: "/web-design",
  UIUX: "/uiux-design",

  WEBDEVELOPMENT: "/web-development",
  FRONTENDDEVELOPMENT: "/frontend-development",
  BACKENDDEVELOPMENT: "/backend-development",
  ECOMMERCEDEVELOPMENT: "/eCommerce-development",
  CMSDEVELOPMENT: "/cms-development",
  MOBILEAPPDEVELOPMENT: "/mobile-app-development",
  MVPDEVELOPMENT: "/mvp-development",
  FRONTENDDEVELOPMENT: "/frontend-development",
  ECOMMERCEDEVELOPMENT: "/eCommerce-development",
  MVPDEVELOPMENT: "/mvp-development",
  NEXTJSDEVELOPMENT: "/nextjs-development",

  SEO:"/seo",
  SMO:"/smo",
  PPC:"/ppc",

  PGI:"/payment-gateway-integration",
  SHIPPINGINTEGRATION:"/shipping-integration",
  SMI:"/social-media-integration",
  TPAI:"/third-party-api-integration",

  SUPPORTANDMAINTENANCE:"/support-maintanance",

  ITCONSULTING:"/it-consulting",
  STARTUPCONSULTING:"/startup-consulting",

  PHPDEVELOPMENT: "/php-development", 
  LARAVELDEVELOPMENT: "/laravel-development", 
  CODEIGNITERDEVELOPMENT: "/codeigniter-development", 
  WORDPRESSDEVELOPMENT: "/wordpress-development", 
  SHOPIFYDEVELOPMENT: "/shopify-development", 
  WEBFLOWYDEVELOPMENT: "/webflow-development", 
  HUBSPOTDEVELOPMENT: "/hubspot-development", 
  REACTNATIVEDEVELOPMENT: "/react-native-development", 
  IONICDEVELOPMENT: "/ionic-development", 
  PROGRESSIVEDEVELOPMENT: "/progressive-development",
  ANGULARJSDEVELOPMENT: "/angular-js-development", 
  EXPRESSJSDEVELOPMENT: "/express-js-development", 
  REACTJSDEVELOPMENT: "/reactjs-development", 
  NODEJSDEVELOPMENT: "/nodejs-development",

  ANDROIDAPPSDEVELOPMENT: "/android-app-development",
  IOSAPPSDEVELOPMENT: "/ios-app-development",
  IPADAPPSDEVELOPMENT: "/iPad-app-development",
  FLUTTERAPPSDEVELOPMENT: "/flutter-app-development",

  DESIGNPROTOTYPE: "/design-prototype",
  MOBILEAPPDESIGN: "/mobile-app-design",
  PSDTOHTML: "/psd-to-html",
  RESPONSIVEWEBDESIGN: "/responsive-web-design",

  BLOG: "/blog",
  SINGLEBLOG: "/single-blog",
  SINGLEBLOG1: "/blog/why-it-is-necessary-to-do-regular-updates-of-your-wordPress-website",
  SINGLEBLOG2: "/blog/wordPress-automation-tools-and-tips",
  SINGLEBLOG3: "/blog/top-things-your-landing-page-should-have",
  SINGLEBLOG4: "/blog/top-Predictions-for-facebook-advertising-in-2021",
  SINGLEBLOG5: "/blog/top-advanced-SEO-techniques-to-Maximize-Your-Search-Traffic",
  SINGLEBLOG6: "/blog/the-best-B2B-marketing-strategies-to-increase-leads",
  SINGLEBLOG7: "/blog/linkedIn-marketing-best-strategies-for-2021",
  SINGLEBLOG8: "/blog/is-managed-wordPress-hosting-worth-the-extra-price",
  SINGLEBLOG9: "/blog/how-will-SEO-change-in-2021",
  SINGLEBLOG10: "/blog/how-web-agencies-can-reduce-production-cost-in-2021",
  SINGLEBLOG11: "/blog/how-to-motivate-and-engage-a-remote-software-team",
  SINGLEBLOG12: "/blog/how-to-avoid-cultural-pitfalls-in-outsourcing",
  SINGLEBLOG13: "/blog/how-to-speed-optimize-wordpress-website",
  SINGLEBLOG14: "/blog/how-to-secure-wordpress-site",
  SINGLEBLOG15: "/blog/how-to-keep-your-wordpress-website-updated",
  SINGLEBLOG16: "/blog/ten-plugins-you-must-have-for-your-wordpress-website",
  SINGLEBLOG17: "/blog/how-to-make-virtual-employees-productive",
  SINGLEBLOG18: "/blog/how-shoulds-i-find-the-right-outsourcing-partner-in-india",
  SINGLEBLOG19: "/blog/a-comparison-between-fixed-price-and-time-and-material-contract",
  SINGLEBLOG20: "/blog/7-signs-its-time-to-consider-outsourcing",
  SINGLEBLOG21: "/blog/top-reasons-to-consider-offshore-development",
  SINGLEBLOG22: "/blog/onshore-vs-offshore-development-which-is-better",
  SINGLEBLOG23: "/blog/offshore-development-best-practices-to-know-about",
  SINGLEBLOG24: "/blog/leading-offshore-development-trends-to-know-about",
  SINGLEBLOG25: "/blog/the-ways-to-utilize-an-effective-outsourcing-strategy-and-achieve-business-success-by-eliminating-the-risks",

  PORTFOLIO: "/portfolio",
  CONFIDENTIALITY: "/confidentiality",
  CONTACT:"/contact",

  USAPIPELINING:"/portfolio/usa-pipelining",

};
export default router;